<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <?php

    echo "Goodbye world b";

    $name = "asstown treadmill";
    $number = "3.1";
    echo "<p> hello $name<p>";
    if ($number * 10 >31){echo "bigger than 31";

    }
    else if
($number = 31 ){echo "equal to 31";

    }
    else {
      echo "smaller than 31";
    }
    $counter = 11;
    $seconds = 1;
    do {
        echo "<p>  $counter <p>" ;
        $counter = $counter-1;
}while ($counter != 0);



    ?>
  </body>
</html>
